CREATE TABLE customers (
    customer_ID INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    fullName VARCHAR(100) NOT NULL,
    address VARCHAR(255),
    city VARCHAR(100),
    password VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    Img VARCHAR(255)
);

CREATE TABLE Orders (
    OrderID INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    OrderDate DATETIME NOT NULL,
    DeliveryDate DATETIME NOT NULL,
    Status VARCHAR(50) NOT NULL,
    TotalPrice INT NOT NULL,
    TotalCapacity INT NOT NULL,
    FOREIGN KEY (username) REFERENCES customers(username) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE product_categories (
    category_ID INT AUTO_INCREMENT PRIMARY KEY,
    category_name VARCHAR(100) NOT NULL,
    category_description VARCHAR(255) NOT NULL
);

CREATE TABLE products (
    product_ID INT AUTO_INCREMENT PRIMARY KEY,
    product_name VARCHAR(100) NOT NULL,
    unit_price INT NOT NULL,
    CapacityPerUnit INT NOT NULL,
    available INT NOT NULL,
    category_ID INT NOT NULL,
    Description VARCHAR(255),
    FOREIGN KEY (category_ID) REFERENCES product_categories(category_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE OrderItems (
    OrderID INT NOT NULL,
    product_ID INT NOT NULL,
    Quantity INT NOT NULL,
    Cost INT NOT NULL,
    FOREIGN KEY (OrderID) REFERENCES Orders(OrderID) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (product_ID) REFERENCES products(product_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE TrainTrips (
    TrainTripID INT AUTO_INCREMENT PRIMARY KEY,
    DepartureTime DATETIME NOT NULL,
    Destination INT NOT NULL,
    AvailableCapacity INT NOT NULL
);

CREATE TABLE Store (
    StoreID INT PRIMARY KEY,
    City VARCHAR(100) NOT NULL,
    ContactNumber INT
);

CREATE TABLE Routes (
    RouteID INT AUTO_INCREMENT PRIMARY KEY,
    StoreID INT NOT NULL,
    Destination VARCHAR(100) NOT NULL,
    TimeToCompletion TIME NOT NULL,
    FOREIGN KEY (StoreID) REFERENCES Store(StoreID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Trucks (
    TruckID INT AUTO_INCREMENT PRIMARY KEY,
    Available BOOL NOT NULL,
    Capacity INT NOT NULL,
    StoreID INT NOT NULL,
    LastHoursUsed INT NOT NULL,
    FOREIGN KEY (StoreID) REFERENCES Store(StoreID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE DriverAssistants (
    DriverAssistantID INT AUTO_INCREMENT PRIMARY KEY,
    StoreID INT NOT NULL,
    WorkHours TIME NOT NULL,
    ConsecutiveTurns INT NOT NULL,
    FOREIGN KEY (StoreID) REFERENCES Store(StoreID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Drivers (
    DriverID INT AUTO_INCREMENT PRIMARY KEY,
    StoreID INT NOT NULL,
    WorkHours TIME NOT NULL,
    ConsecutiveTurns INT NOT NULL,
    FOREIGN KEY (StoreID) REFERENCES Store(StoreID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Shipment (
    DeliveryID INT AUTO_INCREMENT PRIMARY KEY,
    TrainTripID INT NOT NULL,
    OrderID INT NOT NULL,
    TruckID INT NOT NULL,
    DriverID INT NOT NULL,
    DriverAssistantID INT NOT NULL,
    RouteID INT NOT NULL,
    FOREIGN KEY (TrainTripID) REFERENCES TrainTrips(TrainTripID) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (OrderID) REFERENCES Orders(OrderID) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (TruckID) REFERENCES Trucks(TruckID) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (DriverID) REFERENCES Drivers(DriverID) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (DriverAssistantID) REFERENCES DriverAssistants(DriverAssistantID) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (RouteID) REFERENCES Routes(RouteID) ON DELETE RESTRICT ON UPDATE CASCADE
);